version: '3'

services:
  web:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
